net:
  address: 0.0.0.0
  port: 80
  workers: 4
  bufSizeKB: 256
  noDelay: true
  syncBufs: true

http:
  timeout: 1000
  timeoutResolution: 900
  maxPipeline: 100
  serverName: Kona

  mandatoryHeaders:
    connection: true
    contentType: true
